// apps/codingcatdev/src/components/RecentPostsList.tsx
import { Post, PostType } from '@/models/post.model';
import { NextRouter } from 'next/router';
import ActiveLink from '@/components/ActiveLink';
import { isActiveLesson, isActiveLink } from '@/utils/basics/links';

export default function RecentPostsList({
  posts,
  router,
}: {
  posts: Post[];
  router: NextRouter;
}): JSX.Element {
  return (
    <>
      {posts.map((post) => (
        <li
          key={post._id}
          className={`list-none cursor-pointer p-1 rounded m-1 flex flex-col justify-between
        ${
          isActiveLink(router, `/${post._type}/${post.slug}`)
            ? 'bg-primary-900 text-basics-50'
            : 'bg-transparent hover:bg-primary-900 hover:text-basics-50'
        }
        `}
        >
          <ActiveLink
            href={`/${post._type}/${post.slug}`}
            className="no-underline border-none hover:text-basics-50 dark:hover:text-basics-50"
          >
            {post.title}
          </ActiveLink>
        </li>
      ))}
    </>
  );
}

// apps/codingcatdev/src/routes/(content-single)/(non-course)/RecentPostsList.svelte
<script lang="ts">
	import type { Content, ContentType } from '$lib/types';
	import { pluralize } from '$lib/utils';

	export let list: Content[];
	export let contentType: ContentType;
	$: title = pluralize({ type: contentType } as Content);
</script>

<div class="card">
	<header class="card-header capitalize pb-2 text-xl font-bold">{title}</header>
	<hr />
	<ul>
		{#each list as content}
			<li class={`list-none cursor-pointer p-1 rounded m-1 flex flex-col justify-between`}>
				<a href={`/${contentType}/${content.slug}`} class="link-primary">
					{content.title}
				</a>
			</li>
		{/each}
	</ul>
</div>
