// app/(main)/(top-level-pages)/sponsorships/code-with-codingcatdev/page.tsx
import type { Metadata, ResolvingMetadata } from "next";
import { type PortableTextBlock } from "next-sanity";
import { notFound } from "next/navigation";

import PortableText from "@/components/portable-text";

import type { PageQueryResult } from "@/sanity.types";
import { sanityFetch } from "@/sanity/lib/live";
import { pageQuery } from "@/sanity/lib/queries";
import { resolveOpenGraphImage } from "@/sanity/lib/utils";
import { BreadcrumbLinks } from "@/components/breadrumb-links";
import SponsorshipCards from "../sponsorship-cards";
import SponsorshipForm from "../sponsorship-form";
import AJPrimary from "@/components/icons/aj-primary";

type Props = {
  params: false;
};

export async function generateMetadata(
  { params }: Props,
  parent: ResolvingMetadata
): Promise<Metadata> {
  const page = await sanityFetch<PageQueryResult>({
    query: pageQuery,
    params: {
      slug: "code-with-codingcatdev",
    },
    stega: false,
  });
  const previousImages = (await parent).openGraph?.images || [];
  const ogImage = resolveOpenGraphImage(page?.coverImage);

  return {
    title: page?.title,
    description: page?.excerpt,
    openGraph: {
      images: ogImage ? ogImage : previousImages,
    },
  } satisfies Metadata;
}

export default async function SponsorshipsPage() {
  const [page] = await Promise.all([
    sanityFetch<PageQueryResult>({
      query: pageQuery,
      params: {
        slug: "code-with-codingcatdev",
      },
    }),
  ]);

  if (!page?._id) {
    return notFound();
  }

  return (
    <div className="container px-5 mx-auto">
      <BreadcrumbLinks
        links={[
          { title: "Sponsorships", href: "/sponsorships" }
        ]}
      />
      <section className="grid grid-cols-1 gap-2 md:mx-8 md:gap-8 mx-auto prose-violet lg:prose-xl dark:prose-invert">
        <div className="flex flex-col items-center sm:hidden">
          <AJPrimary cls="w-48 h-48" />
        </div>
        <div className="flex justify-center m-4">
          <h1 className="flex flex-col gap-2">
            <span className="text-xl md:text-4xl">Sponsorship for</span>
            <span className="md:text-6xl font-extrabold">
              {" "}
              Code with CodingCat.dev{" "}
            </span>
            <span className="text-xl md:text-2xl">
              a CodingCat.dev Production
            </span>
          </h1>
          <div className="flex-col items-center hidden sm:flex">
            <AJPrimary cls="w-48 h-48" />
          </div>
        </div>
        <div className="flex justify-center bg-muted/50 ">
          <div className="flex flex-col p-8">
            <section className="my-8 flex flex-col gap-1 md:gap-4">
              <p className="">
                On CodingCat.dev your advertisement is{" "}
                <span className="uppercase text-primary font-black text-3xl">
                  permanent
                </span>
                !
              </p>
              <p>
                You read that right, it is not just while you are sponsoring and
                it doesn&apos;t change by the flavor of the week like Carbon or
                Google Ads.
              </p>

              <p>
                Streaming sponsorship is a great way to reach a highly engaged
                audience of potential customers. By sponsoring a stream, your
                company can be featured prominently on the footer of the stream
                of{" "}
                <span className="uppercase font-black text-2xl text-primary">
                  over 16K subscribers
                </span>
                , with the opportunity to reach a large number of viewers who
                are already interested in the topics your video is about.
              </p>
            </section>
          </div>
        </div>
        <SponsorshipForm />
        <div className="flex justify-center bg-muted/50 ">
          <div className="flex flex-col p-8">
            <div className="flex justify-center w-full gap-4 p-8 font-extrabold">
              <p className="text-4xl">
                <span className="text-8xl text-primary"> Why </span>
                <span className="font-bold">
                  would you sponsor live coding?
                </span>
              </p>
            </div>
            <ul>
              <li>
                <strong>Reach a large audience:</strong>
                Live streaming on YouTube and Twitch is a great way to reach a
                large audience. In fact, YouTube Live is one of the most popular
                live streaming platforms in the world, with millions of viewers
                tuning in each day.
              </li>
              <li>
                <strong>Engage with your audience:</strong>
                Live streaming is also a great way to engage with your audience.
                You can interact with viewers in real time, answer questions,
                and get feedback. This can help you build relationships with
                your audience and create a sense of community.
              </li>
              <li>
                <strong>Promote your brand:</strong>
                Live streaming is a great way to promote your brand. You can use
                live streaming to showcase your products or services, announce
                new initiatives, or simply share your company culture. This can
                help you raise awareness of your brand and attract new
                customers.
              </li>
              <li>
                <strong>Drive traffic to your website:</strong>
                Live streaming can also help you drive traffic to your website.
                You can include a link to your website in your live stream
                description, or you can encourage viewers to visit your website
                for more information. This can help you increase website traffic
                and generate leads.
              </li>
            </ul>
          </div>
        </div>
        <div className="flex justify-center bg-muted/50 ">
          <div className="flex flex-col p-8">
            <p>
              If you&apos;re looking for a way to reach a large audience, engage
              with your audience, promote your brand, and drive traffic to your
              website, then sponsoring live YouTube is a great option.
            </p>
          </div>
        </div>
        <SponsorshipCards />
      </section>
    </div>
  );
}

// apps/codingcatdev/src/routes/(top-level-pages)/sponsorships/code-with-codingcatdev/+page.svelte
<script lang="ts">
	import SponsorshipCards from '../SponsorshipCards.svelte';
	import AJPrimary from '$lib/components/global/icons/AJPrimary.svelte';
	import SponsorshipForm from '../SponsorshipForm.svelte';
</script>

<svelte:head>
	<title>Code with CodingCat.dev Sponsorship</title>
	<!-- Meta Tags -->
	<meta name="title" content="Code with CodingCat.dev Sponsorship" />
	<meta name="description" content="Code with CodingCat.dev Sponsorship" />
	<meta name="keywords" content="codingcatdev, webdev, webdevelopment, learning, beginner" />
	<meta name="theme-color" content="#6366f1" />
	<meta name="author" content="CodingCatDev, LLC" />
	<!-- Open Graph - https://ogp.me/ -->
	<meta property="og:site_name" content="Code with CodingCat.dev Sponsorship" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://codingcat.dev/sponsorships" />
	<meta property="og:locale" content="en_US" />
	<meta property="og:title" content="Code with CodingCat.dev Sponsorship" />
	<meta property="og:description" content="Code with CodingCat.dev Sponsorship" />
	<meta
		property="og:image"
		content="https://media.codingcat.dev/image/upload/v1686702324/main-codingcatdev-photo/code-with-ccd-sponsorship.png"
	/>
	<meta
		property="og:image:secure_url"
		content="https://media.codingcat.dev/image/upload/v1686702324/main-codingcatdev-photo/code-with-ccd-sponsorship.png"
	/>
	<meta property="og:image:type" content="image/png" />
	<meta property="og:image:width" content="1920" />
	<meta property="og:image:height" content="1080" />

	<!-- Open Graph: Twitter -->
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:site" content="@CodingCatDev" />
	<meta name="twitter:creator" content="@CodingCatDev" />
	<meta name="twitter:title" content="Sponsorships" />
	<meta name="twitter:description" content="Code with CodingCat.dev Sponsorship" />
	<meta
		name="twitter:image"
		content="https://media.codingcat.dev/image/upload/v1686702324/main-codingcatdev-photo/code-with-ccd-sponsorship.png"
	/>
</svelte:head>

<ol class="breadcrumb">
	<li class="capitalize crumb"><a href="/sponsorships">Sponsorships</a></li>
	<li class="crumb-separator" aria-hidden>&rsaquo;</li>
	<li>Code with CodingCat.dev Sponsorship</li>
</ol>

<section class="grid grid-cols-1 gap-2 mx-2 md:mx-8 md:gap-8 markdown">
	<div class="flex flex-col items-center sm:hidden">
		<AJPrimary cls="w-48 h-48" />
	</div>
	<div class="flex justify-center m-4">
		<h1 class="flex flex-col gap-2">
			<span class="text-xl md:text-4xl">Sponsorship for</span>
			<span class="md:text-6xl font-extrabold"> Code with CodingCat.dev </span>
			<span class="text-xl md:text-2xl">a CodingCat.dev Production</span>
		</h1>
		<div class="flex-col items-center hidden sm:flex">
			<AJPrimary cls="w-48 h-48" />
		</div>
	</div>
	<div class="flex justify-center card variant-soft-surface">
		<div class="flex flex-col p-8">
			<section class="my-8 flex flex-col gap-1 md:gap-4">
				<p class="">
					On CodingCat.dev your advertisement is <span
						class="uppercase bg-surface-backdrop-token dark:text-primary-500 font-black text-3xl p-2 rounded m-1"
						>permanent</span
					>!
				</p>
				<p>
					You read that right, it is not just while you are sponsoring and it doesn't change by the
					flavor of the week like Carbon or Google Ads.
				</p>

				<p>
					Streaming sponsorship is a great way to reach a highly engaged audience of potential
					customers. By sponsoring a stream, your company can be featured prominently on the footer
					of the stream of
					<span class="uppercase font-black text-2xl text-primary-500">over 16K subscribers</span>,
					with the opportunity to reach a large number of viewers who are already interested in the
					topics your video is about.
				</p>
			</section>
		</div>
	</div>
	<SponsorshipForm />
	<div class="flex justify-center card variant-soft-surface">
		<div class="flex flex-col p-8">
			<div class="flex justify-center w-full gap-4 p-8 font-extrabold">
				<p class="text-4xl">
					<span class="text-8xl text-primary-500"> Why </span>
					<span class="font-bold">would you sponsor live coding?</span>
				</p>
			</div>
			<ul>
				<li>
					<strong>Reach a large audience:</strong>
					Live streaming on YouTube and Twitch is a great way to reach a large audience. In fact, YouTube
					Live is one of the most popular live streaming platforms in the world, with millions of viewers
					tuning in each day.
				</li>
				<li>
					<strong>Engage with your audience:</strong>
					Live streaming is also a great way to engage with your audience. You can interact with viewers
					in real time, answer questions, and get feedback. This can help you build relationships with
					your audience and create a sense of community.
				</li>
				<li>
					<strong>Promote your brand:</strong>
					Live streaming is a great way to promote your brand. You can use live streaming to showcase
					your products or services, announce new initiatives, or simply share your company culture.
					This can help you raise awareness of your brand and attract new customers.
				</li>
				<li>
					<strong>Drive traffic to your website:</strong>
					Live streaming can also help you drive traffic to your website. You can include a link to your
					website in your live stream description, or you can encourage viewers to visit your website
					for more information. This can help you increase website traffic and generate leads.
				</li>
			</ul>
		</div>
	</div>

	<p>
		If you're looking for a way to reach a large audience, engage with your audience, promote your
		brand, and drive traffic to your website, then sponsoring live YouTube is a great option.
	</p>
	<SponsorshipCards />
</section>
