// apps/codingcatdev/src/routes/(top-level-pages)/sponsorships/podcast/Podcatchers.svelte
<script lang="ts">
	import Image from '$lib/components/content/Image.svelte';
</script>

<section class="my-20 text-center">
	<div class="flex flex-col">
		<div class="flex flex-wrap justify-center mb-8">
			<a
				href="https://podcasts.apple.com/us/podcast/purrfect-dev/id1491655542"
				target="_blank"
				rel="noreferrer"
				aria-label="Listen on Apple Podcasts"
			>
				<Image
					classes="w-full"
					src="https://media.codingcat.dev/image/upload/v1686688657/main-codingcatdev-photo/podcatchers/applepodcasts-badge.svg"
					alt="Image of Apple Podcasts logo"
				/>
			</a>

			<a
				href="https://open.spotify.com/show/2kiOI0PCB2jXMU0cdqUy4z"
				target="_blank"
				rel="noreferrer"
				aria-label="Listen on Spotify"
			>
				<Image
					classes="w-full"
					src="https://media.codingcat.dev/image/upload/v1686688657/main-codingcatdev-photo/podcatchers/spotify-badge.svg"
					alt="Image of Spotify logo"
				/>
			</a>
		</div>

		<div class="flex flex-wrap justify-center">
			<a
				href="https://www.breaker.audio/purrfect-dot-dev-1"
				target="_blank"
				rel="noreferrer"
				aria-label="Listen on Breaker"
			>
				<Image
					classes="w-full"
					src="https://media.codingcat.dev/image/upload/v1686688657/main-codingcatdev-photo/podcatchers/breaker-badge.svg"
					alt="Image of breaker logo"
				/>
			</a>

			<a
				href="https://podcasts.google.com/?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy8xMTViMjAzYy9wb2RjYXN0L3Jzcw=="
				target="_blank"
				rel="noreferrer"
				aria-label="Listen on Google Podcasts"
			>
				<Image
					classes="w-full"
					src="https://media.codingcat.dev/image/upload/v1686688657/main-codingcatdev-photo/podcatchers/googlepodcasts-badge.svg"
					alt="Image of Google Podcasts logo"
				/>
			</a>

			<a
				href="https://overcast.fm/itunes1491655542/purrfect-dev"
				target="_blank"
				rel="noreferrer"
				aria-label="Listen on Overcast"
			>
				<Image
					classes="w-full"
					src="https://media.codingcat.dev/image/upload/v1686688657/main-codingcatdev-photo/podcatchers/overcast-badge.svg"
					alt="Image of Overcast logo"
				/>
			</a>

			<a
				href="https://pca.st/aysv9xg5"
				target="_blank"
				rel="noreferrer"
				aria-label="Listen on Pocket Casts"
			>
				<Image
					classes="w-full"
					src="https://media.codingcat.dev/image/upload/v1686688657/main-codingcatdev-photo/podcatchers/pocketcasts-badge.svg"
					alt="Image of Pocket Casts logo"
				/>
			</a>

			<a
				href="https://radiopublic.com/purrfectdev-Gy40q4"
				target="_blank"
				rel="noreferrer"
				aria-label="Listen on RadioPublic"
			>
				<Image
					classes="w-full"
					src="https://media.codingcat.dev/image/upload/v1686688657/main-codingcatdev-photo/podcatchers/radiopublic-badge.svg"
					alt="Image of Radio Public logo"
				/>
			</a>

			<a
				href="https://www.stitcher.com/s?fid=491385&refid=stpr"
				target="_blank"
				rel="noreferrer"
				aria-label="Listen on Stitcher"
			>
				<Image
					classes="w-full"
					src="https://media.codingcat.dev/image/upload/v1686688657/main-codingcatdev-photo/podcatchers/stitcher-badge.svg"
					alt="Image of Stitcher logo"
				/>
			</a>
		</div>
	</div>
</section>

// app/(main)/(top-level-pages)/sponsorships/podcast/podcatchers.tsx
import CoverImage from "@/components/cover-image";

export default function Podcatchers() {
  return (
    <section className="my-20 text-center">
      <div className="flex flex-col">
        <div className="grid grid-flow-col gap-4">
          <a
            href="https://podcasts.apple.com/us/podcast/purrfect-dev/id1491655542"
            target="_blank"
            rel="noreferrer"
            aria-label="Listen on Apple Podcasts"
          >
            <CoverImage
              className="w-full h-auto"
              quality={100}
              image={{
                _type: "cloudinary.asset",
                public_id:
                  "main-codingcatdev-photo/podcatchers/applepodcasts-badge",
                context: {
                  _type: "cloudinary.assetContext",
                  custom: {
                    _type: "cloudinary.assetContextCustom",
                    alt: "Image of Apple Podcasts logo",
                  },
                },
              }}
            />
          </a>

          <a
            href="https://open.spotify.com/show/2kiOI0PCB2jXMU0cdqUy4z"
            target="_blank"
            rel="noreferrer"
            aria-label="Listen on Spotify"
          >
            <CoverImage
              className="w-full h-auto"
              quality={100}
              image={{
                _type: "cloudinary.asset",
                public_id: "main-codingcatdev-photo/podcatchers/spotify-badge",
                context: {
                  _type: "cloudinary.assetContext",
                  custom: {
                    _type: "cloudinary.assetContextCustom",
                    alt: "Image of Spotify logo",
                  },
                },
              }}
            />
          </a>
        </div>

        <div className="grid grid-flow-col gap-4">
          <a
            href="https://www.breaker.audio/purrfect-dot-dev-1"
            target="_blank"
            rel="noreferrer"
            aria-label="Listen on Breaker"
          >
            <CoverImage
              className="w-full h-auto"
              quality={100}
              image={{
                _type: "cloudinary.asset",
                public_id: "main-codingcatdev-photo/podcatchers/breaker-badge",
                context: {
                  _type: "cloudinary.assetContext",
                  custom: {
                    _type: "cloudinary.assetContextCustom",
                    alt: "Image of breaker logo",
                  },
                },
              }}
            />
          </a>

          <a
            href="https://overcast.fm/itunes1491655542/purrfect-dev"
            target="_blank"
            rel="noreferrer"
            aria-label="Listen on Overcast"
          >
            <CoverImage
              className="w-full h-auto"
              quality={100}
              image={{
                _type: "cloudinary.asset",
                public_id: "main-codingcatdev-photo/podcatchers/overcast-badge",
                context: {
                  _type: "cloudinary.assetContext",
                  custom: {
                    _type: "cloudinary.assetContextCustom",
                    alt: "Image of Overcast logo",
                  },
                },
              }}
            />
          </a>

          <a
            href="https://pca.st/aysv9xg5"
            target="_blank"
            rel="noreferrer"
            aria-label="Listen on Pocket Casts"
          >
            <CoverImage
              className="w-full h-auto"
              quality={100}
              image={{
                _type: "cloudinary.asset",
                public_id:
                  "main-codingcatdev-photo/podcatchers/pocketcasts-badge",
                context: {
                  _type: "cloudinary.assetContext",
                  custom: {
                    _type: "cloudinary.assetContextCustom",
                    alt: "Image of Pocket Casts logo",
                  },
                },
              }}
            />
          </a>

          <a
            href="https://radiopublic.com/purrfectdev-Gy40q4"
            target="_blank"
            rel="noreferrer"
            aria-label="Listen on RadioPublic"
          >
            <CoverImage
              className="w-full h-auto"
              quality={100}
              image={{
                _type: "cloudinary.asset",
                public_id:
                  "main-codingcatdev-photo/podcatchers/radiopublic-badge",
                context: {
                  _type: "cloudinary.assetContext",
                  custom: {
                    _type: "cloudinary.assetContextCustom",
                    alt: "Image of Radio Public logo",
                  },
                },
              }}
            />
          </a>

          <a
            href="https://www.stitcher.com/s?fid=491385&refid=stpr"
            target="_blank"
            rel="noreferrer"
            aria-label="Listen on Stitcher"
          >
            <CoverImage
              className="w-full h-auto"
              quality={100}
              image={{
                _type: "cloudinary.asset",
                public_id: "main-codingcatdev-photo/podcatchers/stitcher-badge",
                context: {
                  _type: "cloudinary.assetContext",
                  custom: {
                    _type: "cloudinary.assetContextCustom",
                    alt: "Image of Stitcher logo",
                  },
                },
              }}
            />
          </a>
        </div>
      </div>
    </section>
  );
}
