// nextjs/src/layout/NavLinks.tsx
import ActiveLink from '@/components/ActiveLink';
import Blog from '@/components/global/icons/nav/Blog';
import Courses from '@/components/global/icons/nav/Courses';
import Community from '@/components/global/icons/nav/Community';
import Podcasts from '@/components/global/icons/nav/Podcasts';
import Tutorials from '@/components/global/icons/nav/Tutorials';

const navLinks = `grid place-items-center content-between links-secondary`;

const NavLinks = () => {
  return (
    <nav className="flex mx-auto">
      <div className="hidden md:flex md:space-x-4">
        <ActiveLink activeClassName="bg-purple-900" href="/courses">
          <a className={`${navLinks} nav-links`}>
            <Courses />
            Courses
          </a>
        </ActiveLink>
        <ActiveLink activeClassName="bg-purple-900" href="/tutorials">
          <a className={`${navLinks} nav-links`}>
            <Tutorials />
            Tutorials
          </a>
        </ActiveLink>
        <ActiveLink activeClassName="bg-purple-900" href="/podcasts">
          <a className={`${navLinks} nav-links`}>
            <Podcasts className="w-35 h-35" />
            Podcasts
          </a>
        </ActiveLink>
        <ActiveLink activeClassName="bg-purple-900" href="/blog">
          <a className={`${navLinks} nav-links`}>
            <Blog />
            Blog
          </a>
        </ActiveLink>

        <ActiveLink activeClassName="bg-purple-900" href="/community">
          <a className={`${navLinks} nav-links`}>
            <Community />
            Community
          </a>
        </ActiveLink>
      </div>
      <style jsx>{`
        .nav-links:hover {
          filter: brightness(1.5);
        }
      `}</style>
    </nav>
  );
};

export default NavLinks;

// apps/codingcatdev/src/lib/components/layout/NavLinks.svelte
<script lang="ts">
	import NavLink from '$lib/components/layout/NavLink.svelte';
	import Courses from '$lib/components/global/icons/nav/Courses.svelte';
	import Tutorials from '$lib/components/global/icons/nav/Tutorials.svelte';
	import Podcasts from '$lib/components/global/icons/nav/Podcasts.svelte';
	import Blog from '$lib/components/global/icons/nav/Blog.svelte';
	import Schedule from '$lib/components/global/icons/nav/Schedule.svelte';
</script>

<nav class="flex mx-auto">
	<div class="hidden md:flex gap-2 lg:gap-4 md:place-items-center">
		<NavLink href="/courses" name="Courses" component={Courses} />
		<NavLink href="/tutorials" name="Tutorials" component={Tutorials} />
		<NavLink href="/podcasts" name="Podcasts" component={Podcasts} />
		<NavLink href="/schedule" name="Schedule" component={Schedule} />
		<NavLink href="/blog" name="Blog" component={Blog} />
	</div>
</nav>
